const $=s=>document.querySelector(s),content=$("#content"),title=$("#page-title"),subtitle=$("#subtitle");
let page="dashboard",state={agents:[],calls:[],bases:[],numbers:[],usage:null};
const E=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const pretty=d=>d?new Date(d).toLocaleString("vi-VN",{timeZone:"Asia/Ho_Chi_Minh"}):"—";
const rows=d=>Array.isArray(d)?d:Array.isArray(d?.data)?d.data:[];
const txt=(v)=>v===null||v===undefined||v===""?"—":E(v);
const n=v=>Number(v||0).toLocaleString("vi-VN");
const badge=s=>'<span class="badge">'+txt(({queued:"Đang chờ",dialing:"Đang gọi",ringing:"Đổ chuông",in_progress:"Đang nói chuyện",completed:"Hoàn tất",failed:"Thất bại",cancelled:"Đã hủy",no_answer:"Không nghe máy",potential:"Tiềm năng",follow_up:"Cần liên hệ lại",not_interested:"Không quan tâm",processing:"Đang xử lý",ready:"Sẵn sàng"})[s]||s)+'</span>';
function notice(msg,err=false){const el=$("#notice");el.textContent=msg;el.style.background=err?"#991b1b":"#102039";el.style.display="block";clearTimeout(window._toast);window._toast=setTimeout(()=>el.style.display="none",5200)}
async function api(path,options={}){
 const res=await fetch("/api/"+path,{credentials:"same-origin",...options,headers:options.body instanceof FormData?{}:{"content-type":"application/json",...(options.headers||{})}});
 let data;try{data=await res.json()}catch{data={error:"Máy chủ trả về dữ liệu không hợp lệ."}}
 if(!res.ok)throw Error(data.error?.message||data.error||data.message||"Lỗi HTTP "+res.status);
 return data;
}
const send=(path,obj,method="POST")=>api("v1/"+path,{method,body:JSON.stringify(obj)});
const get=path=>api("v1/"+path);
function panel(h,body,action=""){return '<section class="panel"><div class="panel-top"><h2>'+h+'</h2>'+action+'</div>'+body+'</section>'}
function table(headers,items,render){return items.length?'<table><thead><tr>'+headers.map(h=>'<th>'+h+'</th>').join("")+'</tr></thead><tbody>'+items.map(render).join("")+'</tbody></table>':'<div class="empty">Chưa có dữ liệu từ API.</div>'}
function input(name,label,value="",type="text",required=false){return '<label>'+label+'<input name="'+name+'" type="'+type+'" value="'+E(value)+'" '+(required?"required":"")+'></label>'}
function area(name,label,value="",required=false){return '<label>'+label+'<textarea name="'+name+'" '+(required?"required":"")+'>'+E(value)+'</textarea></label>'}
function select(name,label,options,selected=""){return '<label>'+label+'<select name="'+name+'">'+options.map(([v,l])=>'<option value="'+E(v)+'" '+(String(v)===String(selected)?"selected":"")+'>'+E(l)+'</option>').join("")+'</select></label>'}
function setPage(p){page=p;$("#nav").querySelectorAll("button").forEach(b=>b.classList.toggle("active",b.dataset.page===p));const labels={dashboard:["Tổng quan","Tình trạng vận hành thực tế"],agents:["Trợ lý AI","Thiết kế kịch bản hội thoại tiếng Việt"],calls:["Cuộc gọi","Gọi điện thật và xem kết quả"],knowledge:["Kho kiến thức","Quản lý tài liệu của trợ lý AI"],numbers:["Số điện thoại","Số điện thoại được nhà cung cấp cấp"],usage:["Thống kê","Mức sử dụng và chi phí ước tính"],settings:["Cài đặt","Cấu hình kết nối và bảo mật"]};[title.textContent,subtitle.textContent]=labels[p];load()}
async function load(){
 content.innerHTML='<section class="panel">Đang tải dữ liệu trực tiếp…</section>';
 try{
  if(page==="dashboard"){const [calls,agents,usage]=await Promise.all([get("calls?limit=10"),get("agents?limit=50"),get("usage")]);state.calls=rows(calls);state.agents=rows(agents);state.usage=usage;dashboard()}
  if(page==="agents"){state.agents=rows(await get("agents?limit=100"));agents()}
  if(page==="calls"){state.calls=rows(await get("calls?limit=50"));state.agents=rows(await get("agents?limit=100"));calls()}
  if(page==="knowledge"){state.bases=rows(await get("knowledge-bases?limit=100"));knowledge()}
  if(page==="numbers"){const d=await get("phone-numbers");state.numbers=rows(d);numbers()}
  if(page==="usage"){state.usage=await get("usage");usage()}
  if(page==="settings")settings();
  $("#connection").textContent="● API đã kết nối";$("#connection").className="pill ok";
 }catch(e){$("#connection").textContent="● Lỗi kết nối";$("#connection").className="pill err";content.innerHTML=panel("Không tải được dữ liệu",'<p class="error">'+E(e.message)+'</p><button class="ghost" data-action="reload">Thử lại</button>');notice(e.message,true)}
}
function dashboard(){const t=state.usage?.total||{},recent=state.calls;
 content.innerHTML='<div class="cards">'+[["Cuộc gọi",n(t.calls)],["Phút tính phí",n(t.minutes)],["Chi phí USD (ước tính)",t.cost_usd==null?"Chưa có":Number(t.cost_usd).toFixed(2)],["Trợ lý AI",n(state.agents.length)]].map(([h,v])=>'<div class="metric"><small>'+h+'</small><strong>'+v+'</strong></div>').join("")+'</div>'+
 panel("Cuộc gọi gần đây",table(["Mã","Số điện thoại","Trạng thái","Thời gian"],recent,c=>'<tr><td>'+txt(c.id)+'</td><td>'+txt(c.to)+'</td><td>'+badge(c.status)+'</td><td>'+pretty(c.created_at)+'</td></tr>'),'<button class="ghost" data-page="calls">Xem tất cả</button>')+
 panel("Bắt đầu nhanh",'<div class="actions"><button class="primary" data-page="calls">☎ Tạo cuộc gọi</button><button class="ghost" data-page="agents">◉ Thiết lập trợ lý</button><button class="ghost" data-page="knowledge">▤ Kho kiến thức</button></div>');
}
function agents(){content.innerHTML=panel("Danh sách trợ lý",table(["Tên","Giọng đọc","Kho kiến thức","Mặc định","Hành động"],state.agents,a=>'<tr><td><b>'+txt(a.name)+'</b><br><small>'+txt(a.id)+'</small></td><td>'+txt(a.voice)+'</td><td>'+txt(a.knowledge_base_id)+'</td><td>'+(a.is_default?"Có":"Không")+'</td><td><button class="ghost" data-action="edit-agent" data-id="'+E(a.id)+'">Sửa</button> <button class="ghost danger" data-action="del-agent" data-id="'+E(a.id)+'">Xóa</button></td></tr>'),'<button class="primary" data-action="new-agent">+ Tạo trợ lý</button>')+'<div id="editor"></div>'}
function agentForm(a={}){const names=state.bases;$("#editor").innerHTML=panel(a.id?"Cập nhật trợ lý":"Tạo trợ lý",'<form id="agent-form"><div class="form-grid">'+input("name","Tên trợ lý",a.name||"", "text",true)+input("voice","Mã giọng đọc (theo MTDS)",a.voice||"")+input("speed","Tốc độ giọng đọc",a.speed||1,"number")+input("knowledge_base_id","Mã kho kiến thức",a.knowledge_base_id||"")+'</div>'+area("prompt","Kịch bản hội thoại tiếng Việt",a.prompt||"",true)+area("evaluation","Tiêu chí đánh giá sau cuộc gọi",a.evaluation||"")+'<label><input style="width:auto" type="checkbox" name="is_default" '+(a.is_default?"checked":"")+'> Đặt làm trợ lý mặc định</label><div class="actions"><button class="primary">Lưu trực tiếp lên MTDS</button><button type="button" class="ghost" data-action="close-editor">Đóng</button></div></form>');$("#agent-form").onsubmit=async e=>{e.preventDefault();const f=e.target;const b={name:f.elements.namedItem('name').value.trim(),prompt:f.prompt.value,voice:f.voice.value||undefined,speed:Number(f.speed.value)||1,evaluation:f.evaluation.value,knowledge_base_id:f.knowledge_base_id.value||undefined,is_default:f.is_default.checked};try{await send("agents"+(a.id?"/"+encodeURIComponent(a.id):""),b,a.id?"PATCH":"POST");notice("Đã lưu trợ lý vào API.");load()}catch(err){notice(err.message,true)}}}
function calls(){content.innerHTML=panel("Gọi ra bằng AI",'<form id="call-form"><div class="form-grid">'+input("to","Số điện thoại Việt Nam (+84…)", "","tel",true)+select("agent_id","Trợ lý AI",[["","Chọn trợ lý hoặc nhập kịch bản"],...state.agents.map(a=>[a.id,a.name])])+input("from_number","Số gọi đi (tùy chọn)")+input("crm_id","Mã khách hàng (tùy chọn)")+'</div>'+area("prompt","Kịch bản riêng (không bắt buộc nếu đã chọn trợ lý)")+'<p>Chỉ gọi người đã đồng ý nhận liên hệ. Cuộc gọi có thể phát sinh chi phí thực tế.</p><button class="primary" type="submit">☎ Bắt đầu cuộc gọi thực</button></form>')+
 panel("Lịch sử cuộc gọi",table(["Số điện thoại","Trạng thái","Điểm","Ngày","Chi tiết"],state.calls,c=>'<tr><td>'+txt(c.to)+'</td><td>'+badge(c.status)+'</td><td>'+txt(c.score)+'</td><td>'+pretty(c.created_at)+'</td><td><button class="ghost" data-action="detail-call" data-id="'+E(c.id)+'">Xem</button> '+(["queued","dialing","ringing","in_progress"].includes(c.status)?'<button class="ghost danger" data-action="cancel-call" data-id="'+E(c.id)+'">Hủy</button>':"")+'</td></tr>'))+'<div id="detail"></div>';
 $("#call-form").onsubmit=async e=>{e.preventDefault();const f=e.target;const to=f.to.value.trim(),agent_id=f.agent_id.value,prompt=f.prompt.value.trim();if(!/^(\+84|0)\d{9,10}$/.test(to)){notice("Kiểm tra lại số điện thoại.",true);return}if(!agent_id&&!prompt){notice("Cần chọn trợ lý hoặc nhập kịch bản.",true);return}if(!confirm("Bạn xác nhận người nhận đã đồng ý và muốn thực hiện CUỘC GỌI THẬT có thể tính phí?"))return;
 const b={to,...(agent_id?{agent_id}:{}),...(prompt?{prompt}:{}),...(f.from_number.value.trim()?{from_number:f.from_number.value.trim()}:{}),metadata:{...(f.crm_id.value.trim()?{crm_id:f.crm_id.value.trim()}:{})}};
 const btn=f.querySelector("button[type=submit]");btn.disabled=true;try{const result=await send("calls",b);notice("Đã gửi lệnh gọi thực: "+(result.data?.id||result.id||"API đã chấp nhận"));load()}catch(err){notice(err.message,true)}finally{btn.disabled=false}
 }}
async function detailCall(id){const c=await get("calls/"+encodeURIComponent(id)),d=c.data||c;let transcript=d.transcript||[];if(typeof transcript==="string")transcript=[{text:transcript}];$("#detail").innerHTML=panel("Chi tiết cuộc gọi · "+E(id),'<div class="form-grid"><div><p><b>Trạng thái:</b> '+badge(d.status)+'</p><p><b>Thời lượng:</b> '+txt(d.duration)+' giây</p><p><b>Điểm:</b> '+txt(d.score)+'</p></div><div><p><b>Phân loại:</b> '+txt(d.outcome)+'</p><p><b>Tóm tắt:</b> '+txt(d.summary)+'</p><p><b>Chi phí USD:</b> '+txt(d.usage?.cost_usd)+'</p></div></div><h3>Nội dung hội thoại</h3>'+(transcript.length?transcript.map(x=>'<p><b>'+txt(x.role||x.speaker)+'</b>: '+txt(x.text||x.content||JSON.stringify(x))+'</p>').join(""):'<p>Chưa có nội dung hội thoại.</p>')+'<button class="ghost" data-action="recording" data-id="'+E(id)+'">Lấy liên kết ghi âm có thời hạn</button><div id="recording"></div>')}
function knowledge(){content.innerHTML=panel("Các kho kiến thức",table(["Tên kho","Mô tả","Đang xử lý","Thao tác"],state.bases,k=>'<tr><td><b>'+txt(k.name)+'</b></td><td>'+txt(k.description)+'</td><td>'+n(k.processing_count)+'</td><td><button class="ghost" data-action="docs" data-id="'+E(k.id)+'">Tài liệu</button> <button class="ghost danger" data-action="del-kb" data-id="'+E(k.id)+'">Xóa</button></td></tr>'),'<button class="primary" data-action="new-kb">+ Tạo kho kiến thức</button>')+'<div id="editor"></div>'}
async function documents(id){const d=rows(await get("knowledge-bases/"+encodeURIComponent(id)+"/documents"));$("#editor").innerHTML=panel("Tài liệu trong kho",table(["Tên","Trạng thái","Thao tác"],d,x=>'<tr><td>'+txt(x.name)+'</td><td>'+badge(x.status)+'</td><td><button class="ghost danger" data-action="del-doc" data-kb="'+E(id)+'" data-id="'+E(x.id)+'">Xóa</button></td></tr>')+'<form id="doc-form"><div class="form-grid">'+input("name","Tên tài liệu", "", "text",true)+'<label>Tải tài liệu PDF, DOCX, TXT… (tối đa 10 MB)<input type="file" name="file"></label></div>'+area("content","Hoặc nhập nội dung văn bản")+'<button class="primary">Thêm tài liệu thật</button></form>');
 $("#doc-form").onsubmit=async e=>{e.preventDefault();const f=e.target,file=f.querySelector('input[type=file]').files[0];try{if(file){if(file.size>10*1024*1024)throw Error("Tệp vượt 10 MB.");const fd=new FormData();fd.set("file",file);fd.set("name",f.elements.namedItem('name').value);await api("v1/knowledge-bases/"+encodeURIComponent(id)+"/documents",{method:"POST",body:fd})}else{if(!f.content.value.trim())throw Error("Nhập nội dung hoặc chọn tệp.");await send("knowledge-bases/"+encodeURIComponent(id)+"/documents",{name:f.elements.namedItem('name').value,content:f.content.value})}notice("Đã gửi tài liệu lên API.");documents(id)}catch(err){notice(err.message,true)}}}
function numbers(){content.innerHTML=panel("Số điện thoại đã được cấp",table(["Số điện thoại","Trunk","Trạng thái","Hạn mức còn lại","Giờ được gọi"],state.numbers,x=>'<tr><td>'+txt(x.number)+'</td><td>'+txt(x.trunk)+'</td><td>'+txt(x.status)+'</td><td>'+txt(x.quota_remaining??x.quotaRemaining)+'</td><td>'+txt(x.allowed_hours)+'</td></tr>'))+'<p class="muted">Số điện thoại và kết nối SIP do nhà cung cấp quản lý. Giao diện không tự cấp số mới.</p>'}
function usage(){const t=state.usage?.total||{},day=state.usage?.days||state.usage?.daily||[];content.innerHTML='<div class="cards">'+[["Tổng cuộc gọi",n(t.calls)],["Phút tính phí",n(t.minutes)],["Chi phí dự kiến (USD)",t.cost_usd==null?"Chưa có":Number(t.cost_usd).toFixed(3)]].map(([a,b])=>'<div class="metric"><small>'+a+'</small><strong>'+b+'</strong></div>').join("")+'</div>'+panel("Chi tiết từng ngày",table(["Ngày","Cuộc gọi","Phút tính phí","Chi phí USD"],day,x=>'<tr><td>'+txt(x.date||x.day)+'</td><td>'+n(x.calls)+'</td><td>'+n(x.minutes)+'</td><td>'+txt(x.cost_usd)+'</td></tr>'))+'<p>Chi phí hiển thị do API cung cấp, có thể là ước tính hoặc chưa được cấu hình.</p>'}
function settings(){content.innerHTML=panel("Trạng thái tích hợp",'<p><b>API:</b> https://telecom.mtds.vn/api/v1</p><p><b>Chế độ:</b> chuyển tiếp yêu cầu ở Cloudflare Pages Functions; không sử dụng dữ liệu mẫu.</p><p><b>Bảo mật:</b> API key, mật khẩu quản trị và khóa phiên được lưu dưới dạng Secrets trong Cloudflare.</p><p><b>Lưu ý:</b> để hệ thống an toàn cho nhiều người dùng, hãy bật Cloudflare Access và phân quyền người sử dụng.</p><p><b>Kết nối thoại:</b> do MTDS vận hành và cấp số, không thuộc repository SDK này.</p>')}
document.addEventListener("click",async e=>{
 const b=e.target.closest("button");if(!b)return;
 if(b.dataset.page){setPage(b.dataset.page);return}
 const action=b.dataset.action,id=b.dataset.id;
 try{
 if(action==="reload")load();
 if(action==="new-agent")agentForm();
 if(action==="edit-agent"){const x=await get("agents/"+encodeURIComponent(id));agentForm(x.data||x)}
 if(action==="close-editor")$("#editor").innerHTML="";
 if(action==="del-agent"&&confirm("Xóa trợ lý này trên hệ thống thật?")){await api("v1/agents/"+encodeURIComponent(id),{method:"DELETE"});notice("Đã xóa.");load()}
 if(action==="detail-call")await detailCall(id);
 if(action==="cancel-call"&&confirm("Hủy cuộc gọi thực này?")){await api("v1/calls/"+encodeURIComponent(id),{method:"DELETE"});notice("Đã gửi lệnh hủy.");load()}
 if(action==="recording"){const x=await get("calls/"+encodeURIComponent(id)+"/recording"),url=x.data?.url||x.url;if(!url)throw Error("API chưa trả về URL ghi âm.");const box=$("#recording");box.replaceChildren();const a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noopener noreferrer";a.textContent="Nghe hoặc tải ghi âm (liên kết có thời hạn)";box.appendChild(a)}
 if(action==="new-kb"){$("#editor").innerHTML=panel("Tạo kho kiến thức",'<form id="kb-form">'+input("name","Tên kho","", "text",true)+area("description","Mô tả")+'<button class="primary">Lưu trên hệ thống</button></form>');$("#kb-form").onsubmit=async e=>{e.preventDefault();try{await send("knowledge-bases",{name:e.target.elements.namedItem('name').value,description:e.target.description.value});notice("Đã tạo kho.");load()}catch(err){notice(err.message,true)}}}
 if(action==="docs")await documents(id);
 if(action==="del-kb"&&confirm("Xóa kho kiến thức thật?")){await api("v1/knowledge-bases/"+encodeURIComponent(id),{method:"DELETE"});notice("Đã xóa kho.");load()}
 if(action==="del-doc"&&confirm("Xóa tài liệu thật?")){await api("v1/knowledge-bases/"+encodeURIComponent(b.dataset.kb)+"/documents/"+encodeURIComponent(id),{method:"DELETE"});notice("Đã xóa tài liệu.");documents(b.dataset.kb)}
 }catch(err){notice(err.message,true)}
});
$("#refresh").onclick=load;$("#logout").onclick=async()=>{await api("auth/logout",{method:"POST",body:"{}"}).catch(()=>{});$("#app").hidden=true;$("#login").hidden=false};
$("#login-form").onsubmit=async e=>{e.preventDefault();$("#login-error").textContent="";try{await api("auth/login",{method:"POST",body:JSON.stringify({password:e.target.password.value})});e.target.reset();$("#login").hidden=true;$("#app").hidden=false;load()}catch(err){$("#login-error").textContent=err.message}};
(async()=>{try{const x=await api("auth/status");if(x.authenticated){$("#app").hidden=false;load()}else{$("#login").hidden=false}}catch(e){$("#login").hidden=false;$("#login-error").textContent=e.message}})();
